/* The build version, in exactly one place. It used to be typed into two spots
   in the markup, which is a guarantee that one day it will say the wrong
   thing on a build that shipped. build.py reads this and prints it. */
const BENDR_VERSION = "v37.9";

/* ---------------- parameter registry ---------------- */
/* The panel is laid out in four zones. MIX sits under the channel buttons and
   never moves, because it is the desk. The CHANNEL zone follows the signal path
   and is the only part you can reorder. OUT and TOOLS are pinned at the bottom. */
const SECTIONS = [
  {id:"mixer",    name:"BUS 1 \u00b7 TRANSITION",  cls:"mag",  zone:"mix"},
  {id:"mixer2",   name:"BUS 2 \u00b7 TRANSITION",  cls:"mag",  zone:"mix"},
  {id:"mixerM",   name:"MASTER \u00b7 TRANSITION", cls:"mag",  zone:"mix"},
  {id:"layers",   name:"LAYER STACK",          cls:"cyan", zone:"layerdock"},

  {id:"gen",      name:"PATTERN SYNTH",     cls:"cyan", zone:"chain"},
  {id:"frame",    name:"FRAME / POSITION",  cls:"mag",  zone:"chain"},
  {id:"time",     name:"TIME BASE",         cls:"mag",  zone:"chain"},
  {id:"feedback", name:"FEEDBACK / RESCAN", cls:"mag",  zone:"chain"},
  {id:"signal",   name:"COMPOSITE SIGNAL",  cls:"",     zone:"chain"},
  {id:"sync",     name:"SYNC CORRUPTION",   cls:"",     zone:"chain"},
  {id:"vhs",      name:"TAPE TRANSPORT",    cls:"",     zone:"chain"},
  {id:"enhancer", name:"BENT ENHANCER",     cls:"mag",  zone:"chain"},
  {id:"contour",  name:"CONTOUR / PALETTE", cls:"mag",  zone:"chain"},
  {id:"color",    name:"COLOUR STAGE",      cls:"cyan", zone:"chain"},
  {id:"glitch",   name:"GLITCH LAB",        cls:"mag",  zone:"chain"},
  {id:"lab",      name:"SIGNAL LAB",        cls:"mag",  zone:"chain"},
  {id:"flow",     name:"FLOW / MOSH",       cls:"mag",  zone:"chain"},
  {id:"scan",     name:"SCAN PROCESSOR",    cls:"cyan", zone:"chain"},
  {id:"dct",      name:"BLOCK TRANSFORM",   cls:"mag",  zone:"chain"},
  {id:"tdisp",    name:"TIME DISPLACE",     cls:"mag",  zone:"chain"},
  {id:"keyer",    name:"KEYER",             cls:"cyan", zone:"chain"},

  /* the display and the overlay are master, shared by every channel, so they
     belong beside the other master controls in the dock rather than at the
     bottom of a column that is otherwise entirely per-channel */
  {id:"field",    name:"INTERLACE / FIELDS",cls:"",     zone:"outdock"},
  {id:"codec",    name:"CODEC MOSH",        cls:"mag",  zone:"outdock"},
  {id:"crt",      name:"CRT DISPLAY",       cls:"cyan", zone:"outdock"},
  {id:"overlay",  name:"OUTPUT OVERLAY",    cls:"cyan", zone:"outdock"},

  /* morph lives on the PERFORM tab with the snapshots and the recorder,
     because it is the same job: recalling states while it runs */
  {id:"morph",    name:"PRESET MORPH",      cls:"mag",  zone:"perform"},
];
const ZONES = [
  {id:"chain", label:"CHANNEL \u00b7 SIGNAL PATH", note:"Everything belonging to the channel selected above, in the order the signal actually travels: source, framing, frame store, feedback, then the reorderable stages, then the keyer. Drag by the handle to rearrange."},
];
const PDEF = [
  ["abMix","BUS 1 FADER","mixer",0,1,0],
  ["wipeSoft","WIPE SOFT","mixer",0,1,0.03],
  ["wipeDetail","WIPE DETAIL","mixer",0,1,0.3],
  ["wipeX","WIPE CTR X","mixer",-1,1,0],
  ["wipeY","WIPE CTR Y","mixer",-1,1,0],
  ["mixKeyThresh","KEY THRESH","mixer",0,1,0.5],
  ["mixKeySoft","KEY SOFT","mixer",0.01,1,0.2],
  ["mixKeyInv","KEY INVERT","mixer",0,1,0],
  ["mixKeyHue","KEY HUE","mixer",0,1,0.33],
  ["pipX","PIP X","mixer",-1,1,0.45],
  ["pipY","PIP Y","mixer",-1,1,-0.45],
  ["pipSize","PIP SIZE","mixer",0,1,0.35],
  ["pipBorder","PIP BORDER","mixer",0,1,0.12],
  ["edgeAmt","MELT","mixer",0,2,0],
  ["edgeWidth","MELT WIDTH","mixer",0,2,0.3],
  ["edgeHold","MELT HOLD","mixer",0,1.5,0.6],
  ["edgeSwirl","MELT SWIRL","mixer",-1,1,0],
  ["edgeChroma","MELT CHROMA","mixer",0,1,0.5],
  ["edgeCreep","MELT CREEP","mixer",0,1,0.35],
  ["meltZoom","MELT ZOOM","mixer",-1,1,0.3],
  ["meltHue","MELT HUE","mixer",-1,1,0],
  ["meltSoft","MELT SOFTEN","mixer",0,1,0.35],
  ["layOp1","L1 LEVEL","layers",0,1,1],
  ["layKey1","L1 KEY","layers",0,1,0],
  ["layKeyT1","L1 KEY THRESH","layers",0,1,0.5],
  ["layKeyS1","L1 KEY SOFT","layers",0.01,1,0.2],
  ["layKeyH1","L1 KEY HUE","layers",0,1,0.33],
  ["layOp2","L2 LEVEL","layers",0,1,0],
  ["layKey2","L2 KEY","layers",0,1,0],
  ["layKeyT2","L2 KEY THRESH","layers",0,1,0.5],
  ["layKeyS2","L2 KEY SOFT","layers",0.01,1,0.2],
  ["layKeyH2","L2 KEY HUE","layers",0,1,0.33],
  ["layOp3","L3 LEVEL","layers",0,1,0],
  ["layKey3","L3 KEY","layers",0,1,0],
  ["layKeyT3","L3 KEY THRESH","layers",0,1,0.5],
  ["layKeyS3","L3 KEY SOFT","layers",0.01,1,0.2],
  ["layKeyH3","L3 KEY HUE","layers",0,1,0.33],
  ["layOp4","L4 LEVEL","layers",0,1,0],
  ["layKey4","L4 KEY","layers",0,1,0],
  ["layKeyT4","L4 KEY THRESH","layers",0,1,0.5],
  ["layKeyS4","L4 KEY SOFT","layers",0.01,1,0.2],
  ["layKeyH4","L4 KEY HUE","layers",0,1,0.33],
  ["wipeBord","BORDER WIPE","mixer",0,1,0],
  ["wipeBordCol","BORDER COLOUR","mixer",0,1,0],
  ["wipeRep","WIPE MULTI","mixer",1,4,1],
  ["mixKeyGain","KEY GAIN","mixer",0,1,0.5],
  ["mixKeyDens","KEY DENSITY","mixer",0,1,1],
  ["mixKeyEdge","KEY BORDER","mixer",0,1,0],
  ["mixKeyEdgeCol","KEY BORDER COL","mixer",0,1,0],
  ["mixKeyShadow","KEY SHADOW","mixer",0,1,0],
  ["mixDirt","DIRT","mixer",0,1,0],
  ["mixDirtRate","DIRT RATE","mixer",0,1,0.3],
  ["mixDirtDrop","DIRT DROPOUT","mixer",0,1,0.5],
  ["mixDirtCut","DIRT CUT","mixer",0,1,0.4],
  ["mixDirtKnock","DIRT KNOCK","mixer",0,1,0.5],
  ["mixDirtNoise","DIRT NOISE","mixer",0,1,0.35],

  ["cdMix","BUS 2 FADER","mixer2",0,1,0],
  ["wipeSoft2","WIPE SOFT","mixer2",0,1,0.03],
  ["wipeDetail2","WIPE DETAIL","mixer2",0,1,0.3],
  ["wipeX2","WIPE CTR X","mixer2",-1,1,0],
  ["wipeY2","WIPE CTR Y","mixer2",-1,1,0],
  ["mixKeyThresh2","KEY THRESH","mixer2",0,1,0.5],
  ["mixKeySoft2","KEY SOFT","mixer2",0.01,1,0.2],
  ["mixKeyInv2","KEY INVERT","mixer2",0,1,0],
  ["mixKeyHue2","KEY HUE","mixer2",0,1,0.33],
  ["pipX2","PIP X","mixer2",-1,1,0.45],
  ["pipY2","PIP Y","mixer2",-1,1,-0.45],
  ["pipSize2","PIP SIZE","mixer2",0,1,0.35],
  ["pipBorder2","PIP BORDER","mixer2",0,1,0.12],
  ["edgeAmt2","MELT","mixer2",0,2,0],
  ["edgeWidth2","MELT WIDTH","mixer2",0,2,0.3],
  ["edgeHold2","MELT HOLD","mixer2",0,1.5,0.6],
  ["edgeSwirl2","MELT SWIRL","mixer2",-1,1,0],
  ["edgeChroma2","MELT CHROMA","mixer2",0,1,0.5],
  ["edgeCreep2","MELT CREEP","mixer2",0,1,0.35],
  ["meltZoom2","MELT ZOOM","mixer2",-1,1,0.3],
  ["meltHue2","MELT HUE","mixer2",-1,1,0],
  ["meltSoft2","MELT SOFTEN","mixer2",0,1,0.35],
  ["wipeBord2","BORDER WIPE","mixer2",0,1,0],
  ["wipeBordCol2","BORDER COLOUR","mixer2",0,1,0],
  ["wipeRep2","WIPE MULTI","mixer2",1,4,1],
  ["mixKeyGain2","KEY GAIN","mixer2",0,1,0.5],
  ["mixKeyDens2","KEY DENSITY","mixer2",0,1,1],
  ["mixKeyEdge2","KEY BORDER","mixer2",0,1,0],
  ["mixKeyEdgeCol2","KEY BORDER COL","mixer2",0,1,0],
  ["mixKeyShadow2","KEY SHADOW","mixer2",0,1,0],
  ["mixDirt2","DIRT","mixer2",0,1,0],
  ["mixDirtRate2","DIRT RATE","mixer2",0,1,0.3],
  ["mixDirtDrop2","DIRT DROPOUT","mixer2",0,1,0.5],
  ["mixDirtCut2","DIRT CUT","mixer2",0,1,0.4],
  ["mixDirtKnock2","DIRT KNOCK","mixer2",0,1,0.5],
  ["mixDirtNoise2","DIRT NOISE","mixer2",0,1,0.35],

  ["busMix","MASTER FADER","mixerM",0,1,0],
  ["wipeSoftM","WIPE SOFT","mixerM",0,1,0.03],
  ["wipeDetailM","WIPE DETAIL","mixerM",0,1,0.3],
  ["wipeXM","WIPE CTR X","mixerM",-1,1,0],
  ["wipeYM","WIPE CTR Y","mixerM",-1,1,0],
  ["mixKeyThreshM","KEY THRESH","mixerM",0,1,0.5],
  ["mixKeySoftM","KEY SOFT","mixerM",0.01,1,0.2],
  ["mixKeyInvM","KEY INVERT","mixerM",0,1,0],
  ["mixKeyHueM","KEY HUE","mixerM",0,1,0.33],
  ["pipXM","PIP X","mixerM",-1,1,0.45],
  ["pipYM","PIP Y","mixerM",-1,1,-0.45],
  ["pipSizeM","PIP SIZE","mixerM",0,1,0.35],
  ["pipBorderM","PIP BORDER","mixerM",0,1,0.12],
  ["edgeAmtM","MELT","mixerM",0,2,0],
  ["edgeWidthM","MELT WIDTH","mixerM",0,2,0.3],
  ["edgeHoldM","MELT HOLD","mixerM",0,1.5,0.6],
  ["edgeSwirlM","MELT SWIRL","mixerM",-1,1,0],
  ["edgeChromaM","MELT CHROMA","mixerM",0,1,0.5],
  ["edgeCreepM","MELT CREEP","mixerM",0,1,0.35],
  ["meltZoomM","MELT ZOOM","mixerM",-1,1,0.3],
  ["meltHueM","MELT HUE","mixerM",-1,1,0],
  ["meltSoftM","MELT SOFTEN","mixerM",0,1,0.35],
  ["wipeBordM","BORDER WIPE","mixerM",0,1,0],
  ["wipeBordColM","BORDER COLOUR","mixerM",0,1,0],
  ["wipeRepM","WIPE MULTI","mixerM",1,4,1],
  ["mixKeyGainM","KEY GAIN","mixerM",0,1,0.5],
  ["mixKeyDensM","KEY DENSITY","mixerM",0,1,1],
  ["mixKeyEdgeM","KEY BORDER","mixerM",0,1,0],
  ["mixKeyEdgeColM","KEY BORDER COL","mixerM",0,1,0],
  ["mixKeyShadowM","KEY SHADOW","mixerM",0,1,0],
  ["mixDirtM","DIRT","mixerM",0,1,0],
  ["mixDirtRateM","DIRT RATE","mixerM",0,1,0.3],
  ["mixDirtDropM","DIRT DROPOUT","mixerM",0,1,0.5],
  ["mixDirtCutM","DIRT CUT","mixerM",0,1,0.4],
  ["mixDirtKnockM","DIRT KNOCK","mixerM",0,1,0.5],
  ["mixDirtNoiseM","DIRT NOISE","mixerM",0,1,0.35],

  ["morph","MORPH A>B","morph",0,1,0],

  ["genFreqX","FREQ X","gen",0,1,0.18],
  ["genFreqY","FREQ Y","gen",0,1,0.12],
  ["genPhase","PHASE","gen",-1,1,0],
  ["genRate","RATE","gen",-1,1,0.08],
  ["genFM","CROSS MOD","gen",0,1,0],
  ["genFold","WAVEFOLD","gen",0,1,0],
  ["genPulse","PULSE WIDTH","gen",0,1,0.5],
  ["genComp","COMPARATOR","gen",0,1,0],
  ["genThresh","COMP THRESH","gen",0,1,0.5],
  ["genSoft","COMP SOFT","gen",0,1,0.12],
  ["genFoldN","SYMMETRY","gen",1,16,4],
  ["genZoom","SCALE","gen",-1,1,0],
  ["genRot","ROTATE","gen",-1,1,0],
  ["genSkew","SKEW","gen",-1,1,0],
  ["genCX","CENTRE X","gen",-1,1,0],
  ["genCY","CENTRE Y","gen",-1,1,0],
  ["genWarp","DOMAIN WARP","gen",0,1,0],
  ["genHue","HUE","gen",0,1,0.55],
  ["genSpread","HUE SPREAD","gen",0,2,1],
  ["genSat","SATURATION","gen",0,1,0.9],
  ["genBright","BRIGHTNESS","gen",0,1.5,1],
  ["genBands","COLOUR BANDS","gen",2,16,6],

  ["flipMode","FLIP","frame",0,3,0],
  ["mirrorMode","MIRROR","frame",0,3,0],
  ["multiN","MULTI GRID","frame",1,8,1],
  ["srcZoom","ZOOM","frame",-1,1,0],
  ["srcX","POS X","frame",-1,1,0],
  ["srcY","POS Y","frame",-1,1,0],
  ["srcRot","ROTATE","frame",-1,1,0],
  ["kaleido","KALEIDO","frame",0,1,0],
  ["kaleidoN","FOLD N","frame",2,12,3],
  ["kaleidoRot","FOLD SPIN","frame",-1,1,0],
  ["kaleidoX","FOLD CTR X","frame",-1,1,0],
  ["kaleidoY","FOLD CTR Y","frame",-1,1,0],

  ["echo","ECHO","time",0,1,0],
  ["delayF","DELAY FRM","time",1,29,3],
  ["stutter","STUTTER","time",0,1,0],
  ["strobe","STROBE","time",0,1,0],
  ["shake","SHAKE","time",0,1,0],
  ["shakeRate","SHAKE RATE","time",0,1,0.5],

  ["contour","CONTOUR","contour",0,1,0],
  ["contourBands","BANDS","contour",2,40,10],
  ["contourWidth","LINE WIDTH","contour",0.2,6,1.2],
  ["contourHue","LINE HUE","contour",0,1,0],
  ["contourFill","KEEP FILL","contour",0,1,0.25],
  ["lumaSteps","FLATTEN","contour",0,1,0],
  ["stepCount","LEVELS","contour",2,16,5],
  ["dither","DITHER","contour",0,1,0],
  ["mline","MOD LINES","contour",0,1,0],
  ["mlineScale","LINE PITCH","contour",0.25,6,1],
  ["mlineGain","MOD DRIVE","contour",0,3,1.15],
  ["mlineBias","MOD BIAS","contour",-0.5,0.5,0],
  ["mlineFb","ERROR FEED","contour",0,1,0.92],
  ["mlineWin","MOD MEMORY","contour",4,64,32],
  ["mlineTint","KEEP COLOUR","contour",0,1,0],
  ["mlineCol","RGB SEPARATE","contour",0,1,0],
  ["mlineSerp","SERPENTINE","contour",0,1,1],

  ["sparseJit","SPARSE JITTER","lab",0,1,0],
  ["jitThresh","JITTER GATE","lab",0,1,0.7],
  ["ntscArt","NTSC ARTIFACT","lab",0,1,0],
  ["ntscFringe","NTSC FRINGE","lab",0,1,0],
  ["snow","SNOW","lab",0,1,0],
  ["snowAniso","SNOW CLUMP","lab",0,1,0.4],
  ["fmAmt","FM WOBBLE","lab",0,1,0],
  ["fmCarrier","FM CARRIER","lab",0,1,0.35],
  ["slitscan","SLITSCAN","lab",0,1,0],
  ["slitDir","SLIT DIR","lab",0,1,0],
  ["bitCrush","1-BIT CRUSH","lab",0,1,0],
  ["bitScale","CRUSH SCALE","lab",0,1,0.4],
  ["bandKey","BAND KEYER","lab",0,1,0],
  ["bandN","BANDS","lab",2,12,5],
  ["bandHue","BAND HUE","lab",0,1,0.3],
  ["rowSmear","ROW SMEAR","lab",0,1,0],
  ["moire","MOIRE","lab",0,1,0],
  ["moireFreq","MOIRE FREQ","lab",0,1,0.4],
  ["fieldMod","FIELD MOD","lab",0,1,0],
  ["fieldHue","FIELD > HUE","lab",-1,1,0],
  ["fieldWarp","FIELD > WARP","lab",-1,1,0],

  ["pixelSort","PIXEL SORT","glitch",0,1,0],
  ["sortThresh","SORT THRESH","glitch",0,1,0.45],
  ["blockShift","BLOCK TRASH","glitch",0,1,0],
  ["blockSize","BLOCK SIZE","glitch",0,1,0.35],
  ["dotify","HALFTONE","glitch",0,1,0],
  ["dotSize","DOT SIZE","glitch",0,1,0.4],
  ["driftWarp","DRIFT WARP","glitch",0,1,0],
  ["fmWarp","FM WARP","glitch",0,1,0],

  ["mosh","MOSH HOLD","flow",0,0.99,0],
  ["moshGate","MOSH GATE","flow",-1,1,0],
  ["moshVec","P-FRAME PUSH","flow",0,1,0],
  ["flowGain","FLOW GAIN","flow",0,3,1],
  ["flowCurl","CURL / ROTATE","flow",-1,1,0],
  ["melt","MELT","flow",0,1,0],
  ["meltDir","MELT DIR","flow",-1,1,0],
  ["meltGate","MELT GATE","flow",0,1,0],
  ["swirl","SWIRL","flow",0,1,0],
  ["swirlScale","SWIRL SCALE","flow",0,1,0.18],
  ["swirlSpeed","SWIRL SPEED","flow",0,1,0.08],
  ["moshBlock","VECTOR TRASH","flow",0,1,0],
  ["moshBlockSize","TRASH SIZE","flow",0,1,0.68],
  ["moshRate","TRASH RATE","flow",0,1,0.13],
  ["flowStretch","STRETCH","flow",-1,1,0],
  ["flowRepel","EDGE REPEL","flow",-1,1,0],
  ["flowNoise","FLOW NOISE","flow",0,1,0],
  ["flowSharp","RE-SHARP","flow",0,1,0],
  ["flowHue","HUE / PASS","flow",-1,1,0],
  ["flowFade","DECAY / PASS","flow",0,1,0],
  ["timeGrad","TIME SHEAR","flow",-1,1,0],
  ["shearAxis","SHEAR AXIS","flow",0,1,0],

  ["tdAmt","TIME DISPLACE","tdisp",0,1,0],
  ["tdMap","DISPLACE MAP","tdisp",0,4,0],
  ["tdSpread","REACH","tdisp",0,1,0.7],
  ["tdSoft","INTERPOLATE","tdisp",0,1,1],
  ["tdWarp","MAP DRIFT","tdisp",0,1,0],

  ["dctAmt","BLOCK CODEC","dct",0,1,0],
  ["dctQ","QUANTISER","dct",0,1,0.25],
  ["dctTilt","HF PENALTY","dct",0,1,0.5],
  ["dctChroma","CHROMA CRUSH","dct",0,1,0.4],
  ["dctBlock","BLOCK SIZE","dct",0,1,0.35],

  ["pngAmt","FILTER AVALANCHE","lab",0,1,0],
  ["pngDir","AVALANCHE AXIS","lab",0,2,0],
  ["pngRun","AVALANCHE RUN","lab",0,1,0.4],

  ["ampAmt","CLASSIFIER","color",0,1,0],
  ["ampBands","BAND COUNT","color",0,1,0.5],
  ["ampPick","ISOLATE BAND","color",0,1,0],
  ["ampCol","BAND COLOUR","color",0,1,0],
  ["diffAmt","DIFFERENTIATOR","color",0,1,0],
  ["diffScale","DIFF SCALE","color",0,1,0.2],
  ["diffPolar","DIFF DIRECTION","color",0,1,0],
  ["fgPos","CURVE ABOVE","color",-1,1,0],
  ["fgNeg","CURVE BELOW","color",-1,1,0],
  ["fgZero","DEAD ZONE","color",0,1,0],

  ["scanAmt","SCAN DISPLACE","scan",0,1,0],
  ["scanLines","SCAN LINES","scan",60,720,320],
  ["scanSamples","SCAN DETAIL","scan",64,640,256],
  ["scanWidth","BEAM WIDTH","scan",0,1,0.12],
  ["scanVel","VELOCITY GAIN","scan",0,1,0.8],
  ["scanGain","SCAN LEVEL","scan",0,3,1],
  ["scanTiltX","TILT X","scan",-1,1,0],
  ["scanTiltY","TILT Y","scan",-1,1,0],
  ["scanPersp","PERSPECTIVE","scan",0,1,0.3],
  ["scanMono","MONO","scan",0,1,0],
  ["scanHue","COLOURISE","scan",0,1,0],
  ["scanCurve","S-CURVE","scan",-1,1,0],
  ["scanSkew","RASTER SKEW","scan",-1,1,0],
  ["scanCollapse","RASTER COLLAPSE","scan",0,1,0],
  ["scanWobAmt","WOBBLE","scan",0,1,0],
  ["scanWobFreq","WOBBLE FREQ","scan",0,1,0.25],
  ["scanWobLock","WOBBLE LOCK","scan",0,1,1],
  ["scanLissa","LISSAJOUS","scan",0,1,0],

  ["keyThresh","THRESHOLD","keyer",0,1,0.5],
  ["keySoft","SOFTNESS","keyer",0.01,1,0.2],
  ["keyInv","INVERT","keyer",0,1,0],
  ["keyHue","KEY HUE","keyer",0,1,0.33],
  ["keyFx","KEY>FX","keyer",0,1,0],
  ["keyFb","KEY>FB","keyer",0,1,0],

  ["colorize","RAINBOW MAP","enhancer",0,1,0],
  ["colorBands","MAP BANDS","enhancer",0.3,5,1.5],
  ["colorSweep","MAP SWEEP","enhancer",0,1,0.15],
  ["lumaHue","LUMA HUE","enhancer",0,1,0],
  ["sharpEcho","EDGE RING","enhancer",0,1,0],
  ["echoSpace","RING SPACE","enhancer",0,1,0.3],
  ["rgbSep","RGB SPLIT","enhancer",0,1,0],
  ["invFlick","INV FLICKER","enhancer",0,1,0],

  ["fbAmount","AMOUNT","feedback",0,0.97,0],
  ["fbZoom","ZOOM","feedback",-1,1,0],
  ["fbRotate","ROTATE","feedback",-1,1,0],
  ["fbHue","HUE SPIN","feedback",0,1,0],
  ["fbShiftX","SHIFT X","feedback",-1,1,0],
  ["fbShiftY","SHIFT Y","feedback",-1,1,0],
  ["fbShearX","SHEAR X","feedback",-1,1,0],
  ["fbShearY","SHEAR Y","feedback",-1,1,0],
  ["fbGainR","GAIN R","feedback",0,1.5,1],
  ["fbGainG","GAIN G","feedback",0,1.5,1],
  ["fbGainB","GAIN B","feedback",0,1.5,1],
  ["fbSat","SAT / PASS","feedback",0.5,1.5,1],
  ["fbVal","VAL / PASS","feedback",0.5,1.5,1],
  ["fbPost","POSTERIZE","feedback",0,1,0],
  ["fbChromOff","CHROMA OFF","feedback",-1,1,0],
  ["fbBlur","BLUR","feedback",0,1,0],
  ["fbBlur2","BLUR 2 (DoG)","feedback",0,1,0],
  ["fbSharp","SHARPEN","feedback",0,2,0],
  ["fbDrive","DRIVE","feedback",0.2,4,1],
  ["fbPivot","PIVOT","feedback",0,1,0.5],
  ["fbThresh","THRESHOLD","feedback",0,1,0],
  ["fbThreshSoft","THRESH SOFT","feedback",0.005,0.5,0.05],
  ["fbNoise","LOOP NOISE","feedback",0,1,0],
  ["fbNoiseScale","NOISE SCALE","feedback",0,1,0.5],
  ["fbRoll","V ROLL / PASS","feedback",-1,1,0],
  ["fbJitter","SYNC JITTER","feedback",0,1,0],
  ["fbAuto","AUTO LEVEL","feedback",0,1,0],

  ["chromaBleed","CHR BLEED","signal",0,1,0.25],
  ["chromaDelay","CHR DELAY","signal",-1,1,0],
  ["lumaBleed","LUMA BLEED","signal",0,1,0],
  ["bleedDir","BLEED DIR","signal",-1,1,0.5],
  ["vBleed","V BLEED","signal",0,1,0],
  ["rainbow","RAINBOW","signal",0,1,0.1],
  ["dotCrawl","DOT CRAWL","signal",0,1,0.1],
  ["ringing","RINGING","signal",0,1,0.15],
  ["signalNoise","LUMA NOISE","signal",0,1,0.05],
  ["chromaNoise","CHR NOISE","signal",0,1,0.05],

  ["hWobble","H WOBBLE","sync",0,1,0.05],
  ["wobbleFreq","WOB FREQ","sync",0,1,0.2],
  ["tear","TEAR","sync",0,1,0],
  ["tearSize","TEAR SIZE","sync",0,1,0.4],
  ["vRoll","V ROLL","sync",-1,1,0],
  ["jitter","JITTER","sync",0,1,0.1],
  ["humBar","HUM BAR","sync",0,1,0.1],

  ["tapeSpeed","TAPE SPEED","vhs",0,1,0],
  ["tracking","TRACKING","vhs",0,1,0],
  ["trackPhase","TRACK PHASE","vhs",-1,1,0],
  ["trackHunt","SERVO HUNT","vhs",0,1,0],
  ["dropout","DROPOUT","vhs",0,1,0],
  ["dropoutLen","DROPOUT LEN","vhs",0,1,0.35],
  ["chromaLoss","CHROMA LOSS","vhs",0,1,0],
  ["crease","TAPE CREASE","vhs",0,1,0],
  ["creasePos","CREASE POS","vhs",0,1,0.5],
  ["headClog","HEAD CLOG","vhs",0,1,0],
  ["azimuth","AZIMUTH ERR","vhs",0,1,0],
  ["headSwitch","HEAD SW","vhs",0,1,0.3],
  ["tapeWow","TAPE WOW","vhs",0,1,0.15],
  ["wowRate","WOW RATE","vhs",0,1,0.25],
  ["flutter","SCRAPE FLUTTER","vhs",0,1,0],
  ["tapeStretch","TAPE STRETCH","vhs",0,1,0],
  ["edgeDmg","EDGE DAMAGE","vhs",0,1,0],
  ["printThru","PRINT-THROUGH","vhs",0,1,0],
  ["hiss","TAPE HISS","vhs",0,1,0],
  ["stillNoise","STILL FRAME BAR","vhs",0,1,0],
  ["shuttleNz","SHUTTLE BANDS","vhs",0,1,0],
  ["genLoss","GEN LOSS","vhs",0,1,0.1],
  ["genCount","GENERATIONS","vhs",1,12,1],

  ["rGain","RED GAIN","color",0,2,1],
  ["gGain","GREEN GAIN","color",0,2,1],
  ["bGain","BLUE GAIN","color",0,2,1],
  ["saturation","SATURATE","color",0,2.5,1],
  ["hue","HUE","color",0,1,0],
  ["brightness","BRIGHT","color",-1,1,0],
  ["contrast","CONTRAST","color",0.2,2.5,1],
  ["posterize","POSTERIZE","color",0,1,0],
  ["solarize","SOLARIZE","color",0,1,0],
  ["glow","GLOW","color",0,1,0.15],
  ["negative","NEGATIVE","color",0,1,0],
  ["negMode","NEG MODE","color",0,2,0],
  ["monoCol","MONOCOLOR","color",0,1,0],
  ["monoHue","MONO HUE","color",0,1,0.55],
  ["colorPass","COLORPASS","color",0,1,0],
  ["passHue","PASS HUE","color",0,1,0],
  ["passWidth","PASS WIDTH","color",0,1,0.25],
  ["silhouette","SILHOUETTE","color",0,1,0],
  ["silThresh","SIL THRESH","color",0,1,0.45],
  ["silHue","SIL HUE","color",0,1,0.08],
  ["findEdge","FIND EDGE","color",0,1,0],
  ["edgeHue","EDGE HUE","color",0,1,0.45],
  ["emboss","EMBOSS","color",0,1,0],
  ["embossDir","EMBOSS DIR","color",0,1,0.12],

  /* the field domain sits between the mixer and the display: interlace is a
     property of the signal leaving the desk, not of any one channel */
  ["ilAmt","INTERLACE","field",0,1,0],
  ["ilTwitter","LINE TWITTER","field",0,1,0.4],
  ["ilJudder","3:2 JUDDER","field",0,1,0],

  /* a real encode/decode round trip, so these are transport controls for a
     codec rather than numbers feeding a shader */
  ["moshAmt","CODEC MOSH","codec",0,1,0],
  ["moshKey","KEY REMOVAL","codec",0,1,0.95],
  ["moshHold","DELTA HOLD","codec",0,1,0.25],
  ["moshSkip","DELTA DROP","codec",0,1,0],
  ["moshShuffle","CHUNK SHUFFLE","codec",0,1,0],
  ["moshRate","EVENT RATE","codec",0,1,0.5],
  ["moshQ","BITRATE STARVE","codec",0,1,0.35],
  ["moshResync","RESYNC","codec",0,1,0],

  ["scanlines","SCANLINES","crt",0,1,0.18],
  ["beamWidth","BEAM WIDTH","crt",0.1,3,1],
  ["beamShape","BEAM SHAPE","crt",0,1,0.5],
  ["aperture","MASK STRENGTH","crt",0,1,0.12],
  ["maskDark","MASK DARK","crt",0,1,0.5],
  ["curvature","CURVATURE","crt",0,1,0.3],
  ["cornerRound","CORNER","crt",0,1,0.2],
  ["vignette","VIGNETTE","crt",0,1,0.35],
  ["bloom","BLOOM","crt",0,1,0],
  ["bloomRad","BLOOM SIZE","crt",0,1,0.4],
  ["halation","HALATION","crt",0,1,0],
  ["defocus","DEFOCUS","crt",0,1,0],
  ["grain","FILM GRAIN","crt",0,1,0],
  ["outGamma","GAMMA","crt",0.4,2.5,1],
  ["outBright","BRIGHTNESS","crt",-0.5,0.5,0],
  ["outContrast","CONTRAST","crt",0.3,2.5,1],
  ["outSat","SATURATION","crt",0,2,1],
  ["outWarmth","WARMTH","crt",-1,1,0],
  ["blackLevel","BLACK LEVEL","crt",-0.2,0.3,0],
  ["whiteClip","WHITE CLIP","crt",0.5,1.5,1],
  ["phosphor","PERSISTENCE","crt",0,0.95,0],
  ["hvSag","HV SAG","crt",0,1,0],
  ["phosR","PERSIST RED","crt",0,1,0.86],
  ["phosG","PERSIST GREEN","crt",0,1,1],
  ["phosB","PERSIST BLUE","crt",0,1,0.66],

  ["letterbox","LETTERBOX","overlay",0,0.4,0],
  ["pillarbox","PILLARBOX","overlay",0,0.4,0],
  ["bezel","BEZEL","overlay",0,1,0],
  ["glassRefl","GLASS GLARE","overlay",0,1,0],
  ["dust","DUST","overlay",0,1,0],
  ["scratches","SCRATCHES","overlay",0,1,0],
  ["ovMoire","SCREEN MOIRE","overlay",0,1,0],
  ["rollShutter","ROLL SHUTTER","overlay",0,1,0],
  ["safeArea","SAFE GUIDES","overlay",0,1,0],
  ["lensDist","LENS DISTORT","overlay",-1,1,0],
  ["lensCA","LENS FRINGE","overlay",0,1,0],
  ["lensStreak","ANAMORPHIC","overlay",0,1,0],
  ["streakHue","STREAK COLOUR","overlay",0,1,1],
  ["lensSmudge","DIRTY GLASS","overlay",0,1,0],
  ["lightLeak","LIGHT LEAK","overlay",0,1,0],
  ["leakHue","LEAK COLOUR","overlay",0,1,0.05],
  ["gateWeave","GATE WEAVE","overlay",0,1,0],
  ["gateHair","GATE HAIR","overlay",0,1,0],
  ["lcdGrid","LCD GRID","overlay",0,1,0],
  ["stuckPix","STUCK PIXELS","overlay",0,1,0],
  ["osdShow","DECK DISPLAY","overlay",0,1,0],
  ["osdSize","DISPLAY SIZE","overlay",0.4,2,1],
  ["osdGlow","DISPLAY GLOW","overlay",0,1,0.5],
];

